-record(enet_peer,
        {
         handshake_flow,
         local_peer_id,
         remote_ip,
         remote_port,
         name,
         host,
         channels,
         connect_fun
        }).
